google_analytics: G-JPG883L981

header_pages:
  - src/index.md
  - src/projects.md
  - src/blog.md
  - src/docs.md
  - src/about.md
  - src/contact.md

footer: '<p>© 2025 Michael Braun</p>
<p><a href="/contact">Imprint</a> | <a href="/privacypolicy">Privacy Policy</a> | <a href="https://github.com/MichaelBraun1994">GitHub</a></p>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
