# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - src/index.md
  - src/projects.md
  - src/about.md
  - src/contact.md

footer: 'This is just a test.'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
