# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - src/index.md
  - src/projects.md
  - src/docs.md
  - src/about.md
  - src/contact.md

footer: '<p>© 2025 Max Mustermann</p>
<p><a href="/impressum.html">Impressum</a> | <a href="/datenschutz.html">Datenschutz</a></p>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
